# HomeAssistant Config
name: "AxelAI API Server"
description: "API Server for AxelAI"
version: "latest"
slug: "axelai"
init: false
arch:
  - aarch64
  - amd64
image: ghcr.io/nullaxel/axelchatbot

ports:
  8000/tcp: 8000
